# Use python:3.9-slim as the base image
FROM python:3.9-slim

# Set /app as the working directory
WORKDIR /app

# Copy requirements.txt into the image
COPY frontend/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the frontend directory into the image
COPY frontend/ .

# Expose port 8501 (Streamlit's default port)
EXPOSE 8501

# Set the CMD to run Streamlit
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
