# Use python:3.9-slim as the base image
FROM python:3.9-slim

# Set /app as the working directory
WORKDIR /app

# Copy requirements.txt into the image
COPY app/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app directory into the image
COPY app/ .

# Expose port 5000
EXPOSE 5000

# Set the CMD to run the application
CMD ["python", "main.py"]
